# Generated by Django 3.0.3 on 2020-06-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproduct',
            name='img_url',
            field=models.ImageField(default='#', upload_to='img/uploads/'),
        ),
    ]
