# Generated by Django 3.0.3 on 2020-06-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200618_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproduct',
            name='rating',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='allproduct',
            name='tag',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
