# Generated by Django 3.0.3 on 2020-06-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200619_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproduct',
            name='img_url',
            field=models.ImageField(upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='allproduct',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='allproduct',
            name='tag',
            field=models.CharField(max_length=10),
        ),
    ]
