# Generated by Django 3.0.3 on 2020-06-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200619_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproduct',
            name='pub_date',
            field=models.DateField(auto_now=True),
        ),
    ]
