# Generated by Django 3.0.3 on 2020-06-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_allproduct_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproduct',
            name='pub_date',
            field=models.DateField(),
        ),
    ]
