# Generated by Django 3.0.3 on 2020-06-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200619_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproduct',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
